services:
  - type: web
    name: naukri-refresher
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NAUKRI_EMAIL
        sync: false
      - key: NAUKRI_PASSWORD
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: NOTIFY_TO
        sync: false
      - key: ADMIN_TOKEN
        sync: false
